#!/bin/bash -l
# Joshua Goldford
# Feb 03, 2021: Run tfba simulations to find max and min coenzyme ratios at different growth rate cutoffs.

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time, also selected here, is 12 hours.  You can increase this up to 720:00:00 for single processor jobs but your job will take longer to start.
#$ -l h_rt=02:00:00

# Specify which shell to use
#$ -S /bin/bash
# Run on the current working directory
#$ -cwd

# Join standard output and error to a single file
#$ -j y

# Send an email when the job begins and when it ends running
#$ -m be

# module load 
module load miniconda
conda activate coenzymes
module load gurobi

# run python script
python /projectnb2/bioinfor/SEGRE/goldford/CoenzymeSpecificity/coenzymes/assets/pytfba/run_scc_cva.v2.18Feb2021.py